export const JUZ_OPTIONS = Array.from({ length: 30 }, (_, index) => String(30 - index))

export const JUZ_SURAH_MAP: Record<string, string[]> = {
  "30": [
    "An-Naba",
    "An-Nazi'at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Inshiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Ghashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Layl",
    "Ad-Duha",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyinah",
    "Az-Zalzalah",
    "Al-Adiyat",
    "Al-Qari'ah",
    "At-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Ma'un",
    "Al-Kawthar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas"
  ],
  "29": [
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddaththir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat"
  ],
  "28": [
    "Al-Mujadilah",
    "Al-Hashr",
    "Al-Mumtahanah",
    "As-Saff",
    "Al-Jumu'ah",
    "Al-Munafiqun",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim"
  ],
  "27": [
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'ah",
    "Al-Hadid"
  ],
  "26": [
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Adh-Dhariyat"
  ],
  "25": [
    "Az-Zumar",
    "Ghafir",
    "Fussilat"
  ],
  "24": [
    "As-Saffat",
    "Sad",
    "Az-Zumar"
  ],
  "23": [
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "Ya-Sin"
  ],
  "22": ["Al-Ahzab"],
  "21": [
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajdah"
  ],
  "20": ["An-Naml", "Al-Qasas"],
  "19": ["An-Nur", "Al-Furqan", "Ash-Shu'ara"],
  "18": ["Al-Mu'minun", "An-Nur"],
  "17": ["Al-Anbiya", "Al-Hajj"],
  "16": ["Al-Kahf", "Maryam", "Ta-Ha"],
  "15": ["Al-Isra", "Al-Kahf"],
  "14": ["Al-Hijr", "An-Nahl"],
  "13": ["Yusuf", "Ar-Ra'd", "Ibrahim"],
  "12": ["Hud", "Yusuf"],
  "11": ["At-Tawbah", "Yunus", "Hud"],
  "10": ["Al-Anfal", "At-Tawbah"],
  "9": ["Al-A'raf", "Al-Anfal"],
  "8": ["Al-An'am", "Al-A'raf"],
  "7": ["Al-Ma'idah", "Al-An'am"],
  "6": ["An-Nisa", "Al-Ma'idah"],
  "5": ["An-Nisa"],
  "4": ["Ali 'Imran", "An-Nisa"],
  "3": ["Al-Baqarah", "Ali 'Imran"],
  "2": ["Al-Baqarah"],
  "1": ["Al-Fatihah", "Al-Baqarah"]
}
