export const JUZ_OPTIONS = Array.from({ length: 30 }, (_, index) => String(30 - index))

export const JUZ_SURAH_MAP: Record<string, string[]> = {
  "30": [
    "An-Naba'",
    "An-Nazi'at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Insyiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Gasyiyah",
    "Al-Fajr",
    "Al-Balad",
    "Asy-Syams",
    "Al-Lail",
    "Ad-Duha",
    "Al-Insyirah",
    "At-Tin",
    "Al-'Alaq",
    "Al-Qadr",
    "Al-Bayyinah",
    "Az-Zalzalah",
    "Al-'Adiyat",
    "Al-Qari'ah",
    "At-Takasur",
    "Al-'Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraisy",
    "Al-Ma'un",
    "Al-Kautsar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Lahab",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas"
  ],
  "29": [
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddassir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat"
  ],
  "28": [
    "Al-Mujadilah",
    "Al-Hasyr",
    "Al-Mumtahanah",
    "As-Saff",
    "Al-Jumu'ah",
    "Al-Munafiqun",
    "At-Tagabun",
    "At-Talaq",
    "At-Tahrim"
  ],
  "27": [
    "Az-Zariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'ah",
    "Al-Hadid"
  ],
  "26": [
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Az-Zariyat"
  ],
  "25": [
    "Fussilat",
    "Asy-Syura",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jasiyah",
    "Al-Ahqaf"
  ],
  "24": [
    "Az-Zumar",
    "Ghafir",
    "Fussilat"
  ],
  "23": [
    "Ya Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar"
  ],
  "22": ["Al-Ahzab", "Saba'", "Fatir", "Ya Sin"],
  "21": [
    "Al-Qasas",
    "Al-'Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajdah"
  ],
  "20": ["An-Naml", "Al-Qasas"],
  "19": ["Al-Furqan", "Asy-Syu'ara'", "An-Naml"],
  "18": ["Al-Mu'minun", "An-Nur", "Al-Furqan"],
  "17": ["Al-Anbiya", "Al-Hajj"],
  "16": ["Al-Kahf", "Maryam", "Ta Ha"],
  "15": ["Al-Isra'", "Al-Kahf"],
  "14": ["Al-Hijr", "An-Nahl"],
  "13": ["Yusuf", "Ar-Ra'd", "Ibrahim"],
  "12": ["Hud", "Yusuf"],
  "11": ["At-Taubah", "Yunus", "Hud"],
  "10": ["Al-Anfal", "At-Taubah"],
  "9": ["Al-A'raf", "Al-Anfal"],
  "8": ["Al-An'am", "Al-A'raf"],
  "7": ["Al-Ma'idah", "Al-An'am"],
  "6": ["An-Nisa", "Al-Ma'idah"],
  "5": ["An-Nisa"],
  "4": ["Ali Imran", "An-Nisa"],
  "3": ["Al-Baqarah", "Ali Imran"],
  "2": ["Al-Baqarah"],
  "1": ["Al-Fatihah", "Al-Baqarah"]
}
